services:
  nginx:
    image: nginx:alpine
    container_name: nginx-gateway
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-default.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt/live/brainstormy.ru/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
      - /etc/letsencrypt/live/brainstormy.ru/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
      - ./nginx_logs:/var/log/nginx
    restart: unless-stopped
    networks:
      - shared-network
    environment:
      - TZ=Europe/Moscow
    command: >
      sh -c "
      rm -f /var/log/nginx/access.log /var/log/nginx/error.log &&
      touch /var/log/nginx/access.log /var/log/nginx/error.log &&
      nginx -g 'daemon off;'
      "

networks:
  shared-network:
    external: true