services:
  nginx:
    image: nginx:alpine
    container_name: nginx-gateway
    ports:
      - "80:80"
    volumes:
      - ./balancer/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
  backend:
    image: cr.yandex/cn19kjesk3i9p2a4r00n/prod/back:main
    container_name: nest-backend
    expose:
      - "3000"
    environment:
      FOLDER_ID: ${FOLDER_ID}
      API_TOKEN: ${API_TOKEN}
      ENVIRONMENT: ${ENVIRONMENT}
      YANDEX_CLIENT_SECRET: ${YANDEX_CLIENT_SECRET}
    restart: unless-stopped

  frontend:
    image: cr.yandex/cn19kjesk3i9p2a4r00n/prod/front:main
    container_name: vite-frontend
    expose:
      - "80"
    restart: unless-stopped
