global:
  scrape_interval: 5s
  evaluation_interval: 5s
  external_labels:
    monitor: 'custom-metrics-monitor'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# rule_files:
#   - "alerts.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'back-metrics'
    static_configs:
      - targets: ['backend:3000']
    metrics_path: /metrics

  - job_name: 'node-exporter'
    static_configs:
      - targets: 
        - 'node-exporter:9100'
        labels:
          instance: 'main-app'
      - targets: 
        - '10.128.0.26:9100'
        labels:
          instance: 'database'

  - job_name: 'mysql-exporter'
    static_configs:
      - targets: 
        - '10.128.0.26:9104'

  # - job_name: 'nginx-exporter'
  #   static_configs:
  #     - targets: ['nginx-exporter:9113']
  #   metrics_path: /metrics

  - job_name: 'nginx-exporter'
    static_configs:
      - targets: ['nginx:8080']  # Change from nginx-exporter:9113 to nginx:8080
    metrics_path: /stub_status