name: Monitoring ci-cd

on: 
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'monitoring/**'
  pull_request:
    branches:
      - master
    paths:
      - 'monitoring/**'

jobs:
  copy_files:
    name: copy monitoring docker compose and prometheus configuration 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Scp docker compose file and prometheus configuration
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          ssh-keyscan -H $SERVER_HOST >> ~/.ssh/known_hosts

          ssh $SERVER_USER@$SERVER_HOST "mkdir -p ~/monitoring/prometheus"
          ssh $SERVER_USER@$SERVER_HOST "mkdir -p ~/monitoring/grafana"

          scp ./monitoring/prometheus/prometheus.yaml $SERVER_USER@$SERVER_HOST:~/monitoring/prometheus/prometheus.yaml
          scp ./monitoring/prometheus/alerts.yaml $SERVER_USER@$SERVER_HOST:~/monitoring/prometheus/alerts.yaml
          scp ./monitoring/prometheus/alerts.yaml $SERVER_USER@$SERVER_HOST:~/monitoring/prometheus/alerts.yaml
          scp -r ./monitoring/grafana/provisioning $SERVER_USER@$SERVER_HOST:~/monitoring/grafana/provisioning
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_HOST: ${{ secrets.SSH_HOST }}
          SERVER_USER: ${{ secrets.SSH_USER }}
  deploy_monitoring:
    name: deploy monitoring
    needs: copy_files
    runs-on: ubuntu-latest
    steps:
      - name: Deploy the app using docker compose
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: GRAFANA_ADMIN_PASSWORD
          script: |
            docker compose -f docker-compose-monitoring.yaml down
            docker compose -f docker-compose-monitoring.yaml up
        env:
          GRAFANA_ADMIN_PASSWORD: ${{ secrets.GRAFANA_ADMIN_PASSWORD }}
